### ISSUE TITLE
Unclear instructions on how to use the extension

### ISSUE THREAD

**Issue by simgunz** [microsoft/vscode-test-adapter-converter#16]
How is this extension supposed to work? It is not clear from the description.

If I disable Test Explorer UI, its language specific extensions (e.g. Python Test Explorer for Visual Studio Code) get disabled automatically and then the test tab disappears.

How can I use this extension to have for example the test tab for python tests?

**Comment by connor4312** [comment]
You can use it by toggling the setting `testExplorer.useNativeTesting` on!

**Comment by simgunz** [comment]
Thanks I managed to get it working. I am still confused by the instructions

> This is an extension that converts from the Test Explorer UI API into native VS Code testing. When using this, **you will likely want to disable the test explorer UI components**

Basically with this extension installed, I still need to have the Test Explorer UI extension installed but I do not need to install the language specific test adapters?

**Comment by connor4312** [comment]
The Test Explorer UI components are now disabled automatically. I'll update the readme.
