### ISSUE TITLE
This dialog should just apply the setting: `"testExplorer.useNativeTesting": true`

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-test-adapter-converter#2]
![image](https://user-images.githubusercontent.com/2644648/120111596-622e0300-c127-11eb-9b2f-1ed3871552ac.png)

Hit "Yes" get these settings applied:
```
{
    "testExplorer.gutterDecoration": false,
    "testExplorer.codeLens": false,
    "testExplorer.errorDecoration": false,
    "testExplorer.errorDecorationHover": false
}
```

however Test Explorer UI has a setting that (I'm guessing) does all of this?: `"testExplorer.useNativeTesting": true`

**Comment by connor4312** [comment]
The setting doesn't turn off editor decorations, for now.

**Comment by hbenl** [comment]
> The setting doesn't turn off editor decorations, for now.

Yes it does, it disables the entire UI of that extension. If you find a situation where it doesn't, I'd appreciate a bug report.

**Comment by hbenl** [comment]
Furthermore, the extension should check if the user has already set `testExplorer.useNativeTesting` to `true`. It's confusing to show a dialog that offers to do something you have already done. Especially if this extension is the only one installed that uses the new testing API: in that case, the dialog shows up the very moment when you set `testExplorer.useNativeTesting` to `true` for the first time.
