### ISSUE TITLE
Test output seems to be lost

### ISSUE THREAD

**Issue by rjra100** [microsoft/vscode-test-adapter-converter#20]
When using the converter with the CMake Test Explorer extension, we're not seeing any output from the tests. The icons indicating pass/fail etc work fine, of course, but we don't see any textual output indicating what went wrong on failures. The window opened by the "show test output" button just says "The test run did not record any output".
We do see output when using the Test Explorer UI itself, so the CMake Test Explorer must be sending the output, and I assume the issue must be in the conversion layer. Unless I've missed something?

**Comment by connor4312** [comment]
Thanks for the issue! I'm not super familiar with cmake, do you have an example project where this happens?

**Comment by rjra100** [comment]
Unfortunately we're working on a private github enterprise instance so I can't point you at any of our stuff. I think something pretty trivial should be able to reproduce it, though. I've attached a [test.zip](https://github.com/microsoft/vscode-test-adapter-converter/files/7284519/test.zip) containing a (very) simple test which demonstrates the problem for me. Hopefully you can just unzip it and go; there are no dependencies on anything more than a C++ compiler and CMake.

The test shows up OK in the test explorer (it fails, but that's deliberate). When run via the old UI, I get a "Test Explorer" pane in the Output tab:
![old](https://user-images.githubusercontent.com/75089897/135998189-1f50ecd1-f8cf-41d1-a349-3110a1ada4a8.PNG)
When run via the native UI, there's no output in the Output tab. If I hit the "Show Output" button I get a "Test Output" Terminal, but nothing of interest shows up in it:
![native](https://user-images.githubusercontent.com/75089897/135998789-1df423e0-6704-4897-b866-f31627a7e7a6.PNG)

In case it matters, I'm on Windows, but building and running everything in a Docker container via the Remote-Containers extension. The container environment's basically RHEL7 with gcc 7.3 (DTS7).

**Comment by connor4312** [comment]
Thanks, that helped a lot!
