### ISSUE TITLE
Mocha Test Explorer - Mocha tests no longer show root they're coming from (in multi-root workspace)

### ISSUE THREAD

**Issue by jruales** [microsoft/vscode-test-adapter-converter#28]
After using the Test Adapter Converter, the tests just show up as "Mocha" instead of indicating the root in a multi-root workspace they came from.

Before:
![image](https://user-images.githubusercontent.com/1588988/156308959-26e4a6b9-9991-4a00-99bf-3ab5c3c6f45b.png)

After:
![image](https://user-images.githubusercontent.com/1588988/156308680-87034aaf-14e1-4473-af45-1ef76351c8ec.png)

**Comment by jruales** [comment]
Should the version be bumped up to include this fix in the latest release?

**Comment by hbenl** [comment]
Any reason why this doesn't get released?
