### ISSUE TITLE
Publish to open-vsx marketplace

### ISSUE THREAD

**Issue by aeisenberg** [microsoft/vscode-test-adapter-converter#31]
The [open-vsx marketplace](https://open-vsx.org/) is an alternative marketplace for vscode extensions. Historically, we have been publishing [our extension](https://github.com/github/vscode-codeql) both to the vscode marketplace and to open-vsx. However, we can no longer publish to open-vsx since we have a dependency on this extension for our test integration.

I believe that there are other extensions being published in the `ms-code` namespace on open-vsx and you could just use similar infrastructure. It is a fairly straightforward process to publish to both registries. [Here is how we do it for our own extension.](https://github.com/github/vscode-codeql/blob/main/.github/workflows/release.yml#L130-L168)

I would like to help in any way I can.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-test-adapter-converter/issues/6
