### ISSUE TITLE
test.useNativeTesting is Unknown Configuration Setting

### ISSUE THREAD

**Issue by MaxMayya** [microsoft/vscode-test-adapter-converter#37]
Hi,
I'm currently using the following VSCode version:

> Version: 1.75.1 (user setup)
> Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
> Date: 2023-02-08T21:32:34.589Z
> Electron: 19.1.9
> Chromium: 102.0.5005.194
> Node.js: 16.14.2
> V8: 10.2.154.23-electron.0
> OS: Windows_NT x64 10.0.19045
> Sandboxed: No

when I add `test.useNativeTesting` to settings.json, I got "Unknown Configuration Setting"  message when I hover it. In fact, when I click on the settings icon of the **Test Adapter Converter**, I don't get the **Extension Settings** option in the drop list as I do for other extensions.

![image](https://user-images.githubusercontent.com/52531039/221232252-2d1eb53a-f45d-46fb-ba5c-536a7dbe0502.png)

I'm using the 0.1.6 version but I also tried 0.1.5, 0.1.4 and 0.1.0 in vain.
I do not have any other testing plugins installed. These are all the extensions I'm currently using:
![image](https://user-images.githubusercontent.com/52531039/221233165-213634e5-dad5-44d1-81f7-62266e8d25c2.png)

Am I missing anything?

**Comment by connor4312** [comment]
The setting is `testExplorer.useNativeTesting` (see the readme) and is registered by the [test explorer UI](https://github.com/hbenl/vscode-test-explorer) extension, not this one. You need that extension installed for the setting to take effect.

**Comment by MaxMayya** [comment]
Sorry I unintentionally dropped the `Explorer` word. Forgive me but I don't really get it straight. I cannot use this test adapter without the [test explorer UI](https://github.com/hbenl/vscode-test-explorer) being installed? If I do, shall I always use the testing dependent extensions (e.g., [CMake Test Explorer](https://marketplace.visualstudio.com/items?itemName=fredericbonnet.cmake-test-adapter))?
