### ISSUE TITLE
Feature Request: Missing "Show in Test Explorer" lens & status decoration

### ISSUE THREAD

**Issue by lachaib** [microsoft/vscode-test-adapter-converter#4]
Hello,

I've been a big user of Test Explorer UI (and can't show enough gratitude to Holger Benl for this wonderful extension), and I'm currently trying out this test-adapter-converter extension and it is great as well, but there are some functionalities I'm already missing:
* the Lens action to show a test in the test explorer view.
* the little status icon next to the line of the test
* multi-selecting nodes to trigger tests in same run

For more details on my usage, I'm currently working on a project with Pytest and in vscode-insiders.

**Comment by connor4312** [comment]
Here's a quick video in the native testing experience, that I think shows the features you describe: https://memes.peet.io/img/21-07-5711a24f-fe28-4c55-b439-d03644616e96.mp4 (ignore the incorrect 'pass' near the end, the changes were still recompiling)

Are you just saying that you would prefer code lenses instead of gutter decorations to show this information?

**Comment by lachaib** [comment]
Hello,

Although your video shows it, I still can't select multiple nodes (tried Cmd, Shift, Ctrl, Alt, Option).
Also, maybe it's because of not using the same framework, Pytest, but I don't get any gutter decoration with the commands, I still just get lenses to run or debug tests.

**Comment by connor4312** [comment]
Make sure you're using VS Code Insiders for the latest fixes.

**Comment by lachaib** [comment]
I'm already on insiders and even with the pull of today I don't get them

**Comment by connor4312** [comment]
Can you please record a gif of what you see? gifcap.dev is useful

**Comment by lachaib** [comment]
![image](https://user-images.githubusercontent.com/26120426/124554009-c71afe00-de35-11eb-91c0-c8671c87f203.png)
As you can see, no gutter decorations there.

**Comment by connor4312** [comment]
`"testExplorer.useNativeTesting": false` means you won't get the native experience and no decorations are expected.

**Comment by connor4312** [comment]
Code lenses are not yet supported in native testing https://github.com/microsoft/vscode/issues/133338
