### ISSUE TITLE
Causes the extension host to repeatedly crash

### ISSUE THREAD

**Issue by ScottsdaleCoder** [microsoft/vscode-test-adapter-converter#43]
Type: <b>Bug</b>

Happened on app startup

Extension version: 0.1.7
VS Code version: Code - Insiders 1.79.0-insider (2dfb838f494f035099e999f0cd0eff5f1f488a30, 2023-05-26T05:22:45.569Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.37GB (17.68GB free)|
|Process Argv|D:\\Code\\Projects\\misd\\synaptik-web-2 /runAs --crash-reporter-id de8ac813-1c78-422f-a80d-01205f8d070f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
19089226:30680468
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by connor4312** [comment]
This extension doesn't activate or do anything on its own. It's extremely unlikely to be causing a crash. Please use the "Start Extension Bisect" command to diagnose the root cause.
