### ISSUE TITLE
Support navigating to source file

### ISSUE THREAD

**Issue by bltavares** [microsoft/vscode-test-adapter-converter#48]
When I'm testing a project, I'd like to quickly jump to the source of the test to edit the code as needed.
Nowadays, there is no option to visit the file or the test location.

![image](https://github.com/microsoft/vscode-test-adapter-converter/assets/109474/205568c8-9765-4adf-b305-0016155fad25)

Using: rust-analyzer

**Comment by connor4312** [comment]
This is supported by the API, it's up to the extension to provide location information for the test. Please open an issue on the relevant extension.
