### ISSUE TITLE
Crashes extension host

### ISSUE THREAD

**Issue by jul1u5** [microsoft/vscode-test-adapter-converter#54]
Type: <b>Bug</b>

VS Code's whole extension host crashes

Extension version: 0.1.9
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.7.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840HS with Radeon 780M Graphics (16 x 3244)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|30.55GB (23.67GB free)|
|Process Argv|--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --disable-features=WaylandFractionalScaleV1 .|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by connor4312** [comment]
This extension just does some API translation. Crashing is likely caused by the actual test extension. Please provide more info if you think this is not the case.
