### ISSUE TITLE
Publish on open-vsx.org

### ISSUE THREAD

**Issue by hbenl** [microsoft/vscode-test-adapter-converter#6]
Please publish this extension on open-vsx.org as well because otherwise Test Explorer will fail to load for VSCodium users.

**Comment by pm4rcin** [comment]
@connor4312 could you provide the extension to the mentioned marketplace? Many users would be very happy to use it.

**Comment by aeisenberg** [comment]
I am not sure why this issue has been closed. This extension is not available on open vsx. As far as I can tell, this will prevent any extension that declares a depency on `ms-code/vscode-test-adapter-converter` from being published to open-vsx. 

Is there a workaround that I am not aware of?

**Comment by connor4312** [comment]
Didn't realize there wasn't an explainer here. For multiple reasons, we will not publish this extension onto open-vsx. There's nothing to stop someone else from doing so, but it won't be an official package that we publish.

**Comment by hbenl** [comment]
@aeisenberg Are you sure you actually need this dependency? You already depend on `hbenl.vscode-test-explorer` which in turn depends on `ms-code/vscode-test-adapter-converter`. Furthermore I have published the converter extension to open-vsx (as `hbenl.test-adapter-converter`) and the Test Explorer published on open-vsx depends on that converter extension. In other words: if you remove the `ms-code/vscode-test-adapter-converter` dependency from your extension, you should be able to publish to both marketplaces and it should just work.

**Comment by aeisenberg** [comment]
> Didn't realize there wasn't an explainer here. For multiple reasons, we will not publish this extension onto open-vsx. There's nothing to stop someone else from doing so, but it won't be an official package that we publish.

Yes, I actually tried publishing the package myself, but I need to be a member of `ms-vscode`. 



> @aeisenberg Are you sure you actually need this dependency? You already depend on `hbenl.vscode-test-explorer` which in turn depends on `ms-code.vscode-test-adapter-converter`. Furthermore I have published the converter extension to open-vsx (as `hbenl.test-adapter-converter`) and the Test Explorer published on open-vsx depends on that converter extension. In other words: if you remove the `ms-code.vscode-test-adapter-converter` dependency from your extension, you should be able to publish to both marketplaces and it should just work.

Thank you very much for your suggestion. I will try this out to see if it works.
